[version]
current = "1.0.1"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "chore: bumped version to {new_version}"
tag_template = "{new_version}"

[[file]]
src = "Cargo.toml"
search = 'version = "{current_version}"'

[[before_commit]]
name = "Regenerate lockfile"
cmd = "cargo generate-lockfile"

[[before_commit]]
name = "Run tests and pre-commit hooks"
cmd = "maturin develop -r && uv run pytest && pre-commit run --all-files"
